name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "index.ts"
      - "README.md"
      - "./github/workflows/publish.yml"
    tags:
      - "v*"

jobs:
  publish:
    name: test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 16
          - 14
          - 12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - run: npm run build
      - run: npm run test
      - name: generate release changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - if: matrix.node-version == 12
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            ./lib/**/*.ts
