name: Publish

on:
  pull_request:
    branches:
      - main
    paths:
      - '*.md'
      - '.github/workflows/publish.yml'
  push:
    branches:
      - main
    paths:
      - '*.md'
      - '.github/workflows/publish.yml'
  
jobs:
  publish:
    name: test on Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version:
          - 16
          - 14
          - 12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ matrix.node-version }}-modules-${{ hashFiles('**/package-lock.json') }}
      - run: npm install
      - run: npm run build